### ISSUE TITLE
version looks incorrect

### ISSUE THREAD

**Issue by crawld** [teamholtz/FastFuels-Python#18]
After updating setup.py, which gets version from git, the created wheel is called fastfuels-1.0.1_1_g6b9692b-py3-none-any.whl. Is that the correct version? I was expecting fastfuels-1.0.1-py3-none-any.whl.

**Comment by lucaswells** [comment]
Did you create the wheel manually? The GH action is setup to publish to PyPI automatically on a release when you increment the version. I didn't see that string of characters on the last release I issued.

**Comment by crawld** [comment]
Yes, I created it manually to get my local changes. 

I'll make a new git tag after merging my PR.

**Comment by crawld** [comment]
version is good in published release.
